name: Enlightenment

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: artixlinux/base:latest
            volumes:
                - /out
            # https://forums.docker.com/t/mount-permission-denied-inside-container/67991
            # https://stackoverflow.com/a/64710449
            options: --cap-add=SYS_ADMIN --privileged=true

        steps:
            - name: Setup
              run: |
                cd ~
                # modprobe loop
                pacman -Syu --needed --noconfirm artools base-devel git
                buildiso -p base -q > /dev/null || true
                git clone --depth 1 https://github.com/${{ github.repository }} artools-workspace/iso-profiles
                mkdir -p ~/.config/artools
                cp artools-workspace/iso-profiles/workflow-data/artools-iso.conf ~/.config/artools
                buildiso -p base -q || true
                buildiso -p base || (dmesg && false)

            - uses: actions/upload-artifact@v2
              with:
                name: isos
                path: /out
